# GuestViewer Configuration

# Maximum distance (in blocks) a spectator can move from their target
max-distance: 100

# Messages
messages:
  # Message shown to players when they join and are set to spectator mode
  spectator-join: "&cYou are not whitelisted! You have been set to spectator mode."
  
  # Message shown to players when they join and have the bypass permission
  player-join: "&aWelcome back! You are playing in survival mode."
  
  # Message shown when a spectator tries to move beyond the max distance
  distance-warning: "&cYou cannot move more than 100 blocks from the player you are spectating!"
  
  # Message shown when a spectator without chat permission tries to chat
  chat-restricted: "&cYou don't have permission to chat. You are in spectator mode."

# Chat settings
chat:
  # Whether to restrict chat for spectators without permission
  restrict-spectator-chat: true

# Broadcast notifications
broadcast:
  # Whether to broadcast when a player with bypass permission joins
  player-join-enabled: true
  player-join-message: "&e%player% &ahas joined the server."
  
  # Whether to broadcast when a player with bypass permission leaves
  player-quit-enabled: true
  player-quit-message: "&e%player% &chas left the server."
  
  # Whether to broadcast when a spectator joins
  spectator-join-enabled: true
  spectator-join-message: "&7Guest &e%player% &7has joined as a spectator."
  
  # Whether to broadcast when a spectator leaves
  spectator-quit-enabled: true
  spectator-quit-message: "&7Guest &e%player% &7has left the server." 